pub mod dirs;
pub mod help;
pub mod i18n;
pub mod init;
#[cfg(target_os = "linux")]
pub mod linux;
pub mod logging;
pub mod resolve;
#[cfg(target_os = "windows")]
pub mod schtasks;
pub mod singleton;
pub mod window_manager;
