packages:
  - "apps/**/*"
  - "packages/**/*"

allowBuilds:
  "@scarf/scarf": true
  "@swc/core": true
  esbuild: true
  msw: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@json-edit-react/components@1.0.0'
  - '@json-edit-react/themes@1.0.0'
  - '@melloware/react-logviewer@6.6.0'
  - '@turbo/darwin-64@2.11.5'
  - '@turbo/darwin-arm64@2.11.5'
  - '@turbo/linux-64@2.11.5'
  - '@turbo/linux-arm64@2.11.5'
  - '@turbo/windows-64@2.11.5'
  - '@turbo/windows-arm64@2.11.5'
  - json-edit-react@2.0.0
  - turbo@2.11.5
