use super::project_python_version;
use super::types::*;
use crate::module::python_runtime::{PythonOutputChunk, PythonOutputStream};
use crate::{
    config::{IProcessNode, ProcessNodeKind},
    feat::{ProjectPythonStreamRunResult, RunProjectPythonRequest, run_project_python_streaming},
    module::{ipc::IpcServer, python_runtime::PythonRuntime},
};
use anyhow::{Context, Result, bail};
use serde_json::Value;
use std::{
    collections::BTreeMap,
    sync::{Arc, Mutex},
};
use tauri::{AppHandle, ipc::Channel};

impl ProcessNodeRegistry {
    /// Synchronize and execute an installed Process Node through Workrun's
    /// managed Python runtime. The project path and entrypoint always come
    /// from the trusted catalog, never from the IPC caller.
    pub async fn run(
        _app: &AppHandle,
        definition: IProcessNode,
        output: Channel<PythonOutputChunk>,
    ) -> Result<ProjectPythonStreamRunResult> {
        let node = Self::installed_node(definition).await?;

        let python_version = project_python_version(&node.project_path).await?;
        run_project_python_streaming(
            RunProjectPythonRequest {
                project_path: node.project_path,
                script_path: node.definition.entry,
                python_version,
                args: Vec::new(),
            },
            output,
        )
        .await
    }

    /// Run an App while sending output to a native owner rather than directly
    /// to a webview channel. This is what lets a run outlive its source page.
    pub async fn run_with_output(
        definition: IProcessNode,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
        on_started: Option<Arc<dyn Fn(u32) + Send + Sync>>,
    ) -> Result<ProjectPythonStreamRunResult> {
        let node = Self::installed_node(definition).await?;
        let python_version = project_python_version(&node.project_path).await?;
        let sync = PythonRuntime::sync_dependencies(&node.project_path, &python_version).await?;
        let ipc = IpcServer::global().create_session().await?;
        let execution = PythonRuntime::run_python_streaming_with_env_and_stdin(
            &sync.environment,
            &node.definition.entry,
            &[],
            &[
                ("WORKRUN_IPC_ENDPOINT".into(), ipc.endpoint.clone()),
                ("WORKRUN_IPC_TOKEN".into(), ipc.token.clone()),
                ("WORKRUN_RUN_ID".into(), ipc.id.clone()),
            ],
            None,
            on_output,
            on_started,
        )
        .await;
        ipc.close().await;
        Ok(ProjectPythonStreamRunResult {
            sync,
            execution: execution?,
        })
    }

    pub async fn run_for_workflow(
        definition: IProcessNode,
        input: &Value,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
    ) -> Result<WorkflowProcessNodeRun> {
        if definition.kind != ProcessNodeKind::Workflow {
            bail!("Tool App `{}` cannot run as a workflow node", definition.id);
        }
        Self::run_with_input(definition, input, "process.result", on_output).await
    }

    /// Invoke a Tool App with the JSON object generated by an Agent.
    pub async fn run_for_tool(
        definition: IProcessNode,
        input: &Value,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
    ) -> Result<WorkflowProcessNodeRun> {
        if definition.kind != ProcessNodeKind::Tool {
            bail!("Workflow App `{}` cannot run as an Agent tool", definition.id);
        }
        Self::run_with_input(definition, input, "tool.result", on_output).await
    }

    async fn run_with_input(
        definition: IProcessNode,
        input: &Value,
        result_type: &str,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
    ) -> Result<WorkflowProcessNodeRun> {
        let node = Self::installed_node(definition).await?;
        let input = apply_input_defaults(input, &node.definition.inputs)?;
        validate_payload(&input, &node.definition.inputs, "input")?;
        let python_version = project_python_version(&node.project_path).await?;
        let sync = PythonRuntime::sync_dependencies(&node.project_path, &python_version).await?;
        let mut ipc = IpcServer::global().create_session().await?;
        ipc.grant_artifacts(&input).await?;
        let input = serde_json::to_vec(&input).context("failed to serialize input for Process Node")?;
        let logs = Arc::new(Mutex::new((String::new(), String::new())));
        let captured_logs = Arc::clone(&logs);
        let execution = PythonRuntime::run_python_streaming_with_env_and_stdin(
            &sync.environment,
            &node.definition.entry,
            &[],
            &[
                ("WORKRUN_IPC_ENDPOINT".into(), ipc.endpoint.clone()),
                ("WORKRUN_IPC_TOKEN".into(), ipc.token.clone()),
                ("WORKRUN_RUN_ID".into(), ipc.id.clone()),
            ],
            Some(&input),
            Arc::new(move |chunk| {
                let mut logs = captured_logs.lock().expect("Process Node log lock poisoned");
                let target = match chunk.stream {
                    PythonOutputStream::Stdout => &mut logs.0,
                    PythonOutputStream::Stderr => &mut logs.1,
                };
                append_output(target, &chunk.data);
                on_output(chunk);
            }),
            None,
        )
        .await;

        let result = if execution.as_ref().is_ok_and(|run| run.exit_code == Some(0)) {
            std::iter::from_fn(|| ipc.try_receive())
                .find(|message| message.get("type").and_then(Value::as_str) == Some(result_type))
                .and_then(|message| message.get("data").cloned())
                .filter(Value::is_object)
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "Process Node `{}` exited without {result_type}({{...}})",
                        node.definition.name,
                    )
                })
        } else {
            Ok(Value::Null)
        };
        let result = match result {
            Ok(value) => match validate_payload(&value, &node.definition.outputs, "output") {
                Ok(()) => ipc.validate_artifact_result(&value).await.map(|_| value),
                Err(error) => Err(error),
            },
            Err(error) => Err(error),
        };
        ipc.close().await;
        let execution = execution?;
        let (stdout, stderr) = std::mem::take(&mut *logs.lock().expect("Process Node log lock poisoned"));
        if execution.exit_code != Some(0) {
            bail!(
                "Process Node `{}` exited with code {}\n{}",
                node.definition.name,
                execution
                    .exit_code
                    .map_or_else(|| "unknown".into(), |code| code.to_string()),
                stderr
            );
        }
        Ok(WorkflowProcessNodeRun {
            definition: node.definition,
            execution,
            stdout,
            stderr,
            result: result?,
        })
    }

    async fn installed_node(definition: IProcessNode) -> Result<ProcessNode> {
        let id = definition.id.clone();
        let node = Self::with_installation(definition).await;
        // Team drafts already have a local authoring project, so they can run before publication.
        if !matches!(
            node.install_status,
            ProcessNodeInstallStatus::Installed | ProcessNodeInstallStatus::Draft
        ) {
            bail!("Process Node is not available locally: {id}");
        }
        Ok(node)
    }
}

fn apply_input_defaults(input: &Value, schemas: &BTreeMap<String, Value>) -> Result<Value> {
    let mut input = input.clone();
    let state = input
        .as_object_mut()
        .context("Process Node input must be a JSON object")?;
    for (name, schema) in schemas {
        if !state.contains_key(name)
            && let Some(default) = schema.get("default")
        {
            state.insert(name.clone(), default.clone());
        }
    }
    Ok(input)
}

fn validate_payload(value: &Value, fields: &BTreeMap<String, Value>, kind: &str) -> Result<()> {
    let mut schema = super::tool_definition::object_schema(fields);
    // Workflow nodes receive a scoped State snapshot, including fields they do
    // not declare. Validate declared fields without rejecting those siblings.
    schema["additionalProperties"] = Value::Bool(true);
    let validator =
        jsonschema::validator_for(&schema).with_context(|| format!("Process Node {kind} schema is invalid"))?;
    if let Some(error) = validator.iter_errors(value).next() {
        // Report the path, never the rejected value: it may contain raw input.
        if let jsonschema::error::ValidationErrorKind::Required { property } = error.kind() {
            bail!(
                "Process Node {kind} is missing required field {property} at {}",
                error.instance_path()
            );
        }
        bail!(
            "Process Node {kind} does not match its schema at {}",
            error.instance_path()
        );
    }
    Ok(())
}

const MAX_WORKFLOW_LOG_CHARS: usize = 200_000;

fn append_output(current: &mut String, chunk: &str) {
    current.push_str(chunk);
    if current.len() > MAX_WORKFLOW_LOG_CHARS {
        let mut keep_from = current.len() - MAX_WORKFLOW_LOG_CHARS;
        while !current.is_char_boundary(keep_from) {
            keep_from += 1;
        }
        current.replace_range(..keep_from, "[Earlier output truncated]\n");
    }
}

#[cfg(test)]
mod tests {
    use super::{MAX_WORKFLOW_LOG_CHARS, append_output, apply_input_defaults, validate_payload};
    use serde_json::json;
    use std::collections::BTreeMap;

    #[test]
    fn fills_only_missing_input_fields_from_schema_defaults() {
        let schemas = BTreeMap::from([
            ("branch".to_string(), json!({"type": "string", "default": "main"})),
            ("limit".to_string(), json!({"type": "integer", "default": 250})),
        ]);

        let result = apply_input_defaults(&json!({"branch": "release"}), &schemas).unwrap();

        assert_eq!(result, json!({"branch": "release", "limit": 250}));
    }

    #[test]
    fn validates_declared_fields_without_rejecting_scoped_state_siblings() {
        let fields = BTreeMap::from([
            (
                "document".into(),
                json!({"type":"object", "required":["$type"], "properties":{"$type":{"const":"artifact"}}}),
            ),
            ("label".into(), json!({"type":"string", "x-workrun-optional":true})),
        ]);
        assert!(
            validate_payload(
                &json!({"document":{"$type":"artifact"}, "question":"extra state"}),
                &fields,
                "input"
            )
            .is_ok()
        );
        assert!(
            validate_payload(&json!({}), &fields, "input")
                .unwrap_err()
                .to_string()
                .contains("document")
        );
        let error = validate_payload(&json!({"document":"private-input-value"}), &fields, "input")
            .unwrap_err()
            .to_string();
        assert!(error.contains("/document"));
        assert!(!error.contains("private-input-value"));
        assert!(validate_payload(&json!({"anything":true}), &BTreeMap::new(), "output").is_ok());
    }

    #[test]
    fn validates_generated_resource_output_contract() {
        let contract: serde_json::Value = serde_json::from_str(include_str!(
            "../../../../../../packages/python-sdk/examples/pdf-process/contract.json"
        ))
        .unwrap();
        let fields = serde_json::from_value(contract["outputs"].clone()).unwrap();
        assert!(validate_payload(&json!({"pageCount":2}), &fields, "output").is_err());
        assert!(
            validate_payload(
                &json!({"pageCount":2,"textPageCount":2,"warnings":[],"report":"/tmp/report.txt","processedPdf":{}}),
                &fields,
                "output"
            )
            .is_err()
        );
    }

    #[test]
    fn truncates_large_unicode_logs_at_a_character_boundary() {
        let mut logs = String::new();
        append_output(&mut logs, &"中".repeat(MAX_WORKFLOW_LOG_CHARS));
        assert!(logs.starts_with("[Earlier output truncated]\n"));
        assert!(logs.ends_with('中'));
    }
}
