use super::project_python_version;
use super::types::*;
use crate::module::python_runtime::{PythonOutputChunk, PythonOutputStream};
use crate::{
    core::handle,
    feat::{ProjectPythonStreamRunResult, RunProjectPythonRequest, run_project_python_streaming},
    module::{ipc::IpcServer, python_runtime::PythonRuntime},
};
use anyhow::{Context, Result, bail};
use serde_json::Value;
use std::{
    collections::BTreeMap,
    sync::{Arc, Mutex},
};
use tauri::{AppHandle, ipc::Channel};

impl ProcessNodeRegistry {
    /// Synchronize and execute an installed Process Node through Workrun's
    /// managed Python runtime. The project path and entrypoint always come
    /// from the trusted catalog, never from the IPC caller.
    pub async fn run(
        app: &AppHandle,
        id: &str,
        output: Channel<PythonOutputChunk>,
    ) -> Result<ProjectPythonStreamRunResult> {
        let node = Self::inspect(id).await?;
        if !matches!(node.install_status, ProcessNodeInstallStatus::Installed) {
            bail!("Process Node is not installed: {id}");
        }

        let python_version = project_python_version(&node.project_path).await?;
        run_project_python_streaming(
            app,
            RunProjectPythonRequest {
                project_path: node.project_path,
                script_path: node.definition.entry,
                python_version,
                args: Vec::new(),
            },
            output,
        )
        .await
    }

    pub async fn run_for_workflow(
        id: &str,
        input: &Value,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
    ) -> Result<WorkflowProcessNodeRun> {
        if Self::inspect(id).await?.definition.kind != ProcessNodeKind::Workflow {
            bail!("Tool App `{id}` cannot run as a workflow node");
        }
        Self::run_with_input(id, input, "process.result", on_output).await
    }

    /// Invoke a Tool App with the JSON object generated by an Agent.
    pub async fn run_for_tool(
        id: &str,
        input: &Value,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
    ) -> Result<WorkflowProcessNodeRun> {
        if Self::inspect(id).await?.definition.kind != ProcessNodeKind::Tool {
            bail!("Workflow App `{id}` cannot run as an Agent tool");
        }
        Self::run_with_input(id, input, "tool.result", on_output).await
    }

    async fn run_with_input(
        id: &str,
        input: &Value,
        result_type: &str,
        on_output: Arc<dyn Fn(PythonOutputChunk) + Send + Sync>,
    ) -> Result<WorkflowProcessNodeRun> {
        let node = Self::inspect(id).await?;
        if !matches!(node.install_status, ProcessNodeInstallStatus::Installed) {
            bail!("Process Node is not installed: {id}");
        }

        let python_version = project_python_version(&node.project_path).await?;
        let app = handle::Handle::app_handle();
        let sync = PythonRuntime::sync_dependencies(app, &node.project_path, &python_version).await?;
        let mut ipc = IpcServer::global().create_session().await?;
        let input = apply_input_defaults(input, &node.definition.inputs)?;
        let input = serde_json::to_vec(&input).context("failed to serialize input for Process Node")?;
        let logs = Arc::new(Mutex::new((String::new(), String::new())));
        let captured_logs = Arc::clone(&logs);
        let execution = PythonRuntime::run_python_streaming_with_env_and_stdin(
            &sync.environment,
            &node.definition.entry,
            &[],
            &[
                ("WORKRUN_IPC_ENDPOINT".into(), ipc.endpoint.clone()),
                ("WORKRUN_IPC_TOKEN".into(), ipc.token.clone()),
                ("WORKRUN_RUN_ID".into(), ipc.id.clone()),
            ],
            Some(&input),
            Arc::new(move |chunk| {
                let mut logs = captured_logs.lock().expect("Process Node log lock poisoned");
                let target = match chunk.stream {
                    PythonOutputStream::Stdout => &mut logs.0,
                    PythonOutputStream::Stderr => &mut logs.1,
                };
                append_output(target, &chunk.data);
                on_output(chunk);
            }),
        )
        .await;

        let result = if execution.as_ref().is_ok_and(|run| run.exit_code == Some(0)) {
            std::iter::from_fn(|| ipc.try_receive())
                .find(|message| message.get("type").and_then(Value::as_str) == Some(result_type))
                .and_then(|message| message.get("data").cloned())
                .filter(Value::is_object)
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "Process Node `{}` exited without {result_type}({{...}})",
                        node.definition.name,
                    )
                })
        } else {
            Ok(Value::Null)
        };
        ipc.close().await;
        let execution = execution?;
        let (stdout, stderr) = std::mem::take(&mut *logs.lock().expect("Process Node log lock poisoned"));
        if execution.exit_code != Some(0) {
            bail!(
                "Process Node `{}` exited with code {}\n{}",
                node.definition.name,
                execution
                    .exit_code
                    .map_or_else(|| "unknown".into(), |code| code.to_string()),
                stderr
            );
        }
        Ok(WorkflowProcessNodeRun {
            definition: node.definition,
            execution,
            stdout,
            stderr,
            result: result?,
        })
    }
}

fn apply_input_defaults(input: &Value, schemas: &BTreeMap<String, Value>) -> Result<Value> {
    let mut input = input.clone();
    let state = input
        .as_object_mut()
        .context("Process Node input must be a JSON object")?;
    for (name, schema) in schemas {
        if !state.contains_key(name) {
            if let Some(default) = schema.get("default") {
                state.insert(name.clone(), default.clone());
            }
        }
    }
    Ok(input)
}

const MAX_WORKFLOW_LOG_CHARS: usize = 200_000;

fn append_output(current: &mut String, chunk: &str) {
    current.push_str(chunk);
    if current.len() > MAX_WORKFLOW_LOG_CHARS {
        let keep_from = current.len() - MAX_WORKFLOW_LOG_CHARS;
        current.replace_range(..keep_from, "[Earlier output truncated]\n");
    }
}

#[cfg(test)]
mod tests {
    use super::apply_input_defaults;
    use serde_json::json;
    use std::collections::BTreeMap;

    #[test]
    fn fills_only_missing_input_fields_from_schema_defaults() {
        let schemas = BTreeMap::from([
            ("branch".to_string(), json!({"type": "string", "default": "main"})),
            ("limit".to_string(), json!({"type": "integer", "default": 250})),
        ]);

        let result = apply_input_defaults(&json!({"branch": "release"}), &schemas).unwrap();

        assert_eq!(result, json!({"branch": "release", "limit": 250}));
    }
}
